### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by jewpaltz** [oriordac/web-dev-app-project#3]
https://github.com/oriordac/web-dev-app-project/blob/0efeb3bdcede6604f7c98c8f0e31ba864b666437/server/models/Liquid.js#L22

I've seen this pattern now by 4 students in this class.
How does one write code like this?
Did you have a professor that wrote code like this?

The only time I've ever seen anything like this is in a comic strip or in a lecture for beginner programmers explaining why you need parameters to functions. Expecting the first year students that have no experience to realize on their own how absolutely ridiculous something like this would be.

This must have gotten into the global consciousness of the class somehow.

**Comment by oriordac** [comment]
Dear Rabbi Plotkin, 
My Liquid.vue file was one of the first files I created for this project. It was my first time experimenting with Vue and its functionality. Before starting the program, I was a history/math student, so this project is my first big web development project. I apologize for its simplicity.
I will say that I had nine unique clones and over 900 views on this project the week the final project was due. I used this simple example to help my friends (Megan, Mike, and Ron) when we were first starting out, but I have helped no one else. I can only assume people used my project as scaffolding for their own designs.

**Comment by jewpaltz** [comment]
B"H

> scaffolding 
that is very generous of you.
More like trying to plagiarize but being too stupid to get it right.
I am very frustrated with a large part of the class to say the least.

Thank you for giving me at least one student that I can be proud of.
